### ISSUE TITLE
Add README.md file

### ISSUE THREAD

**Issue by fatuk** [sofa-fatuk/tonejs#1]
@sofa-fatuk Добавь файл README.md в корень проекта. 
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet. Напиши там про то, что это учебный проект. Напиши как его запускать, как кодить и все такое. И можно по-русски

**Comment by fatuk** [comment]
@sofa-fatuk README text has a mistake: There should be: **This is a training project**

**Comment by sofa-fatuk** [comment]
сделано
