### ISSUE TITLE
Create branch gh-page

### ISSUE THREAD

**Issue by fatuk** [sofa-fatuk/tonejs#2]
@sofa-fatuk Сделай локально ветку **gh-page** и запушь ее сюда. Прочитай что делает ветка **gh-page** в проектах https://htmlacademy.ru/blog/99-github-as-hosting. Это такой хостинг для статических страниц. Ссылка будет вида https://[username].github.io/[reponame]

**Comment by sofa-fatuk** [comment]
готово
